version: "3.9"

services:

  broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    restart: unless-stopped

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-producer

    privileged: true

    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"

    depends_on:
      - broker

    command: >
      python producer.py
      --device-id pir-motion-sensor-01
      --pin 17
      --broker broker
      --topic environments/environment-01/wastebins/wastebin-01/sensors/pir-01/events
      --clean-session False
      --qos 1
      --sample-interval 0.1
      --cooldown 5
      --min-high 0.2
      --duration 60
      --verbose

    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-consumer

    depends_on:
      - broker

  volumes:
  - ./output:/lab6/output

    command: >
      python consumer.py
      --broker broker
      --topic environments/environment-01/wastebins/wastebin-01/sensors/pir-01/events
      --clean-session False
      --qos 1
      --cache-size 100
      --consumer-delay 0.0
      --duration 60
      --out /lab6/output/events.jsonl
      --verbose

    restart: unless-stopped
